### ISSUE TITLE
Public files management

### ISSUE THREAD

**Issue by BenoitSafari** [Cinevoraces/cinevoraces#122]
## Share public files between Front/Back using docker volumes
We've decided to store every public files (avatars, posters...) in a docker volume shared between back and front.

### Back
- [x] Share public folders
- [x] Save and store local posters
- [x] Save and store local avatars
- [x] Compress every avatar using cloudinary, then save them to the public volume.
- [x] ~~Periodically purge cloudinary storage~~ Purge Cloudinary on each upload.

### Front
- [x] Change images sources with correct path for posters
- [x] Change images sources with correct path for avatars
- [x] Add an option to update all TMDB poster links in DB in backoffice (It downloads every poster)
> *A route has been created for that purpose*  
> `/admin/movies/update-posters`
- [x] Update poster randomizer function on home page  
> *A route has been created for that purpose*  
>
> ![image](https://user-images.githubusercontent.com/88612813/214575310-5d14dc6c-dd85-416c-aac7-8406d374afad.png)

**Comment by Julien-Goletto** [comment]
Front-end implementation is done.

Struggling with shared volume sin production mode.
