### ISSUE TITLE
Setting Eslint / Prettier

### ISSUE THREAD

**Issue by BenoitSafari** [Cinevoraces/cinevoraces#5]

**Comment by anthonyespirat** [comment]
https://github.com/Cinevoraces/cinevoraces/commit/2810b2b7ecf3730cea7f05425f26cde12db9d1e2

**Comment by BenoitSafari** [comment]
I'm reopenning this issue since there's no `eslintrc` file in the project.
Also the `settings.json` file in `.vscode` should have `editor.codeActionsOnSave` set to **`source.fixAll.eslint`**.

```json
{
  "eslint.format.enable": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "eslint.workingDirectories": ["./app", "./api"]
}

```

**Comment by BenoitSafari** [comment]
Added ESlint config to back-end based on front-end config.
See [#2de2c37](https://github.com/Cinevoraces/cinevoraces/commit/2de2c37982aa63caddb84ad32fa5ed933b24f518).

I'm closing this issue.
