### ISSUE TITLE
[API-APP] - handleLogin - allow connection with both pseudo and email

### ISSUE THREAD

**Issue by Julien-Goletto** [Cinevoraces/cinevoraces#59]
Small fix for Auth module and better UX :

- [x] Update `getPrivateUser()`/`handleLogin()` methods
- [x] Updating dev-docs
- [x] Updating APP - Connection form accordingly
- [x] Don't return mail address in response as it is not used for user navigation

**Comment by BenoitSafari** [comment]
https://github.com/Cinevoraces/cinevoraces/pull/82

Continue front dev using this branch

**Comment by BenoitSafari** [comment]
Re-opening issue for front task

**Comment by Julien-Goletto** [comment]
PR client side done.

Beware for feedback message :

```
Object { user: {…}, token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQsInBzZXVkbyI6IkxpbG91Iiwicm9sZSI6InVzZXIiLCJleHBpcmVzSW4iOiIxbSIsImlhdCI6MTY3MTgxMjg2OH0.lzMheR1c55rgApzu8Vm5iCo_f1gcM62q6osmvSt2sTg", message: "Bienvenue undefined !" }
​
**message: "Bienvenue undefined !"**
​
token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQsInBzZXVkbyI6IkxpbG91Iiwicm9sZSI6InVzZXIiLCJleHBpcmVzSW4iOiIxbSIsImlhdCI6MTY3MTgxMjg2OH0.lzMheR1c55rgApzu8Vm5iCo_f1gcM62q6osmvSt2sTg"
​
user: Object { id: "34", pseudo: "Lilou", role: "user", … }
```

In case of login with mail, the feedback message doesn't display the pseudo as expected ^^
