### ISSUE TITLE
API - Changing prop name for login returned message

### ISSUE THREAD

**Issue by Julien-Goletto** [Cinevoraces/cinevoraces#60]
Returns currently : {
  "user": {
    "id": "string",
    "pseudo": "string",
    "mail": "string",
    "role": "string",
    "avatar_url": "string"
  },
  "token": "string",
  "response": "string"
}

Should return a message property instead, to harmonize with the whole rest of endpoints and facilitate message toasting.

**Comment by BenoitSafari** [comment]
You actually need the `token` and `user` object so if I understand correctly you want:
```json
{
  "user": { "..." },
  "token": "someString",
  "message": "user logged lol"
}
```
