### ISSUE TITLE
API - Fetching season numbers and associated years

### ISSUE THREAD

**Issue by Julien-Goletto** [Cinevoraces/cinevoraces#75]
Currently there is no way to retrieve years, only season count is sent with metrics.
I don't think adding another dedicated module is relevant, but we can just maybe modify the metrics module to send the seasons array as well ?

**Comment by BenoitSafari** [comment]
I'll create a season endpoint as an detailled object is not really a count/metric mesure.

**Comment by BenoitSafari** [comment]
I'm currently preventing season creation from being superior to number 99.
This is an arbritary limit, but I don't think Cinevoraces will still be live in a century so I guess we don't really care.
```javascript
  description: `
  **Create new season and all associated episodes (proposition slots).**
  `,
  tags: ['Seasons'],
  body: {
    type: 'object',
    properties: {
      year: { type: 'number', minimum: 1, maximum: 3000 },
      season_number: { type: 'number', minimum: 1, maximum: 99 },
    },
  },
```
